name: Build and Deploy GitBook

on:
  push:
    branches:
      - master  # 触发主分支推送事件时执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install GitBook CLI
      run: npm install -g gitbook-cli

    - name: Install dependencies
      run: npm install gitbook-plugin-sitemap-general && gitbook install

    - name: Build GitBook
      run: gitbook build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.BOOKS_TOKEN }}
        publish_dir: ./_book
